version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - monitoring

  grafana-agent:
    image: grafana/agent:latest
    ports:
      - "8009:12345"
    volumes:
      - ./grafana-agent.yml:/etc/grafana-agent.yml
    command: ["-config.file=/etc/grafana-agent.yml"]
    environment:
      - GRAFANA_USERNAME=2694807
      - GRAFANA_API_TOKEN=${GRAFANA_API_TOKEN}
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: