version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - monitoring

  grafana-agent:
    image: grafana/agent:latest
    ports:
      - "9090:9090"
    volumes:
      - ./agent-config.yml:/etc/agent/agent.yml
    command: ["-config.file=/etc/agent/agent.yml"]
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: